//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms
{
    public partial class Default
    {

    }
}