//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.NursingHome
{
    public partial class Residents
    {

    }
}