//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Reports
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.GridView gvEnt;
        protected global::System.Web.UI.WebControls.GridView gvBL;
    }
}