//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Finance
{
    public partial class TransactionNew
    {
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.DropDownList ddlDir;
        protected global::System.Web.UI.WebControls.DropDownList ddlCat;
        protected global::System.Web.UI.WebControls.DropDownList ddlPaidBy;
        protected global::System.Web.UI.WebControls.DropDownList ddlBL;
        protected global::System.Web.UI.WebControls.TextBox txtAmt;
        protected global::System.Web.UI.WebControls.DropDownList ddlCp;
        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;
        protected global::System.Web.UI.WebControls.DropDownList ddlAssoc;
        protected global::System.Web.UI.WebControls.TextBox txtDesc;
        protected global::System.Web.UI.WebControls.DropDownList ddlAllocEntity;
        protected global::System.Web.UI.WebControls.DropDownList ddlAllocBL;
        protected global::System.Web.UI.WebControls.TextBox txtAllocAmt;
        protected global::System.Web.UI.WebControls.TextBox txtAllocNote;
        protected global::System.Web.UI.WebControls.Button btnAddAlloc;
        protected global::System.Web.UI.WebControls.GridView gvAlloc;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}