//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Finance
{
    public partial class Transactions
    {
        protected global::System.Web.UI.WebControls.TextBox txtFrom;
        protected global::System.Web.UI.WebControls.TextBox txtTo;
        protected global::System.Web.UI.WebControls.DropDownList ddlEnt;
        protected global::System.Web.UI.WebControls.Button btnFilter;
        protected global::System.Web.UI.WebControls.Button btnCsv;
        protected global::System.Web.UI.WebControls.GridView gv;
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}