//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Associations
{
    public partial class Associations
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlProp;
        protected global::System.Web.UI.WebControls.DropDownList ddlEnt;
        protected global::System.Web.UI.WebControls.TextBox txtAmt;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}