//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Associations
{
    public partial class Charges
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlAssoc;
        protected global::System.Web.UI.WebControls.TextBox txtY;
        protected global::System.Web.UI.WebControls.TextBox txtM;
        protected global::System.Web.UI.WebControls.TextBox txtAmt;
        protected global::System.Web.UI.WebControls.Button btnGen;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}