//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Associations
{
    public partial class Meetings
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlAssoc;
        protected global::System.Web.UI.WebControls.TextBox txtDT;
        protected global::System.Web.UI.WebControls.TextBox txtTitle;
        protected global::System.Web.UI.WebControls.TextBox txtAgenda;
        protected global::System.Web.UI.WebControls.TextBox txtMinutes;
        protected global::System.Web.UI.WebControls.TextBox txtDec;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}