//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Associations
{
    public partial class Payments
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlAssoc;
        protected global::System.Web.UI.WebControls.DropDownList ddlUnit;
        protected global::System.Web.UI.WebControls.TextBox txtDate;
        protected global::System.Web.UI.WebControls.TextBox txtAmt;
        protected global::System.Web.UI.WebControls.TextBox txtY;
        protected global::System.Web.UI.WebControls.TextBox txtM;
        protected global::System.Web.UI.WebControls.Button btnAdd;
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtRY;
        protected global::System.Web.UI.WebControls.TextBox txtRM;
        protected global::System.Web.UI.WebControls.Button btnRun;
        protected global::System.Web.UI.WebControls.GridView gv;
    }
}