//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace PropertyOpsWebForms.Master
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.Label lblUser;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}